// Generated by dts-bundle-generator v9.5.1

export declare const options: unique symbol;
export interface CookieOptions {
	expires?: number | Date;
	path?: string;
	domain?: string;
	secure?: boolean;
	nulltoremove?: boolean;
	autojson?: boolean;
	autoencode?: boolean;
	encode?: (val: string) => string;
	decode?: (val: string) => string;
	fallback?: false | ((key: string, opt: CookieOptions) => unknown);
	test?: (res: string) => void;
}
export interface CookieEngine extends CookieOptions {
	(key: string): unknown;
	(data: Record<string, unknown>, opt?: CookieOptions): CookieEngine;
	[key: string]: unknown;
}
type CookieStore$1 = Record<string, unknown> & {
	get [options](): CookieEngine;
	set [options](v: Partial<CookieOptions>);
};
export declare const cookies: CookieStore$1;
export declare const local: Record<string, unknown>;
export declare const session: Record<string, unknown>;
export interface DbStore {
	(): Promise<Record<string, unknown>>;
	name: unknown;
	length: unknown;
	[key: string]: unknown;
}
declare const _default: DbStore;
declare const _default$1: (obj: object, key: PropertyKey, cb: (...args: unknown[]) => unknown) => ReturnType<typeof setInterval>;
export type Id = ReturnType<typeof setInterval>;
declare const _default$2: (input: Id | ((...args: unknown[]) => unknown)) => void;

export {
	_default as db,
	_default$1 as subscribe,
	_default$2 as unsubscribe,
};

export {};
